disabled_rules:
  - trailing_whitespace
  - type_name

line_length: 300

excluded:
- Pods
- SceneDelegate.swift
- AppDelegate.swift

type_body_length:
- 400
- 600

variable_name_max_length:
- 60
- 80


